version: "3.8"

services:
  # Grafana
  grafana:
    image: grafana/grafana:12.1.1
    expose:
      - 3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_healthy
    networks:
      - monitor-net

  # Loki Logging
  loki:
    image: grafana/loki:3.5.4
    expose:
      - 3100
    volumes:
      - ./config/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:3100/ready"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - monitor-net

  # Prometheus Metrics
  prometheus:
    image: prom/prometheus:v2.55.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    expose:
      - 9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:9090/-/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - monitor-net

  # Grafana Alloy - Node Exporter
  node-exporter:
    image: grafana/alloy:latest
    hostname: node-exporter
    command: >
      run --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy/config.alloy
    depends_on:
      prometheus:
        condition: service_healthy
    env_file:
      - .env
    expose:
      - 12345
    volumes:
      - ./config/conf-grafana.alloy:/etc/alloy/config.alloy
      # Node Exporter metrics
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - monitor-net

  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.27.2
    ports:
      - "${NGINX_PORT}:80"
    env_file:
      - .env
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - grafana
      - loki
      - prometheus
    restart: unless-stopped
    networks:
      - monitor-net

volumes:
  loki_data:
    name: loki_data_${ENV}
  prometheus_data:
    name: prometheus_data_${ENV}
  grafana_data:
    name: grafana_data_${ENV}

networks:
  monitor-net:
    name: ${DOCKER_NETWORK_NAME}
    driver: bridge