server {
    listen 80;
    server_name _;

    # Grafana
    location / {
        proxy_pass http://grafana:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    # Prometheus
    location /prometheus/api/v1/write {
        auth_basic "MetricsPush";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass http://prometheus:9090/api/v1/write;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
