apiVersion: 1
contactPoints:
  - orgId: 1
    name: slack-contact
    receivers:
      - uid: slack
        type: slack
        disableResolveMessage: false
        settings:
          url: ${SLACK_WEBHOOK_URL}
          username: "Grafana Monitor"
          icon_url: "https://grafana.com/static/assets/img/fav32.png"
          color: '{{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "critical" }}#DC3545{{ else if eq .CommonLabels.severity "warning" }}#FFC107{{ else if eq .CommonLabels.severity "info" }}#6C757D{{ else }}#DC3545{{ end }}{{ else }}#28A745{{ end }}'
          title: '{{ .CommonLabels.alertname }}'
          text: |
            🏢 *Team:* {{ .CommonLabels.team }}
            {{ range .Alerts }}
            🏗️ *Job:* {{ .Annotations.job }}
            🌍 *Environment:* {{ .Annotations.environment }}
            📝 *Summary:* {{ .Annotations.summary }}
            📄 *Description:* {{ .Annotations.description }}
            {{ end }}
