apiVersion: 1

groups:
  - name: application_alerts.generic
    orgId: 1
    folder: Application
    interval: 30s
    rules:
      # Application Down
      - uid: application_down
        title: "🚨 Application Down"
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: |
                (up{job=~".*-metrics"} == 0) and (up{job=~".*-metrics"} offset 5m == 0)
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    type: query_result
                    params: [A]
                  reducer:
                    type: last
                    params: []
                  type: query
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions
        noDataState: OK
        execErrState: Alerting
        for: 3m
        annotations:
          job: "{{ range $values }}{{ .Labels.job }}{{ end }}"
          environment: "{{ range $values }}{{ .Labels.env }}{{ end }}"
          summary: "Application Down 🚨"
          description: "Application is down"
        labels:
          severity: critical
          team: development

      # Application Unhealthy
      - uid: application_unhealthy
        title: "🚨 Application Unhealthy"
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: |
                (healthcheck{job=~".*-metrics"} == 0) and (healthcheck{job=~".*-metrics"} offset 5m == 0)
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    type: query_result
                    params: [A]
                  reducer:
                    type: last
                    params: []
                  type: query
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions
        noDataState: OK
        execErrState: Alerting
        for: 3m
        annotations:
          job: "{{ range $values }}{{ .Labels.job }}{{ end }}"
          environment: "{{ range $values }}{{ .Labels.env }}{{ end }}"
          summary: "Application Unhealthy 🚨"
          description: "Application is unhealthy"
        labels:
          severity: critical
          team: development

      # Application Error Warning
      - uid: application_error
        title: "⚠️ Application Error Warning"
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: loki
            model:
              expr: |
                count_over_time({job=~".*-logs", level="ERROR"}[1m])
              intervalMs: 1000
              maxDataPoints: 43200

          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              reducer: last
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params: [0]
                    type: gt
                  operator:
                    type: and
                  query:
                    type: query_result
                    params: [A]
                  reducer:
                    type: last
                    params: []
                  type: query
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions

        noDataState: OK
        execErrState: Alerting
        for: 0m

        annotations:
          job: "{{ range $values }}{{ .Labels.job }}{{ end }}"
          environment: "{{ range $values }}{{ .Labels.env }}{{ end }}"
          summary: "Application Error Warning ⚠️"
          description: "Application has ERROR logs in the last 30s"

        labels:
          severity: warning
          team: development
